import {  Roboto } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import {  ToastContainer } from 'react-toastify';
import AuthProvider from "./_components/AuthProvider";



const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700"] });


export const metadata = {
  title: "Skiasis",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session, ...pageProps }) {
 
  return (
    <html suppressHydrationWarning lang="en">
    < AuthProvider  >
      <body className={roboto.className}>
            <ToastContainer />
            {children}
      </body>
    </AuthProvider>
    </html>


  );
}
